create table house
(
    house_id     bigint(200) auto_increment
        primary key,
    address      varchar(1000)  not null,
    des          varchar(10000) null,
    house_name   varchar(1000)  not null,
    numBathrooms int            not null,
    numBedrooms  int            not null,
    price        float          not null,
    type_id      bigint         null,
    sourcePath   varchar(255)   not null,
    owner_id     bigint         null
)
    engine = MyISAM;

create index FK4r0nxoot9tsovfbhhopg2mhi
    on house (owner_id);

create index FKoyh55b0ttt5x0cd0odrd2kwek
    on house (type_id);

INSERT INTO house_renting.house (house_id, address, des, house_name, numBathrooms, numBedrooms, price, type_id, sourcePath, owner_id) VALUES (11, 'Tổ 9 xã Phương Độ, Hà Giang', 'Sự sang trọng tự nhiên và mộc mạc trong một không gian khép kín mô tả rõ nhất Maison Teahouse Homestay. Độc đáo vì những lý do đúng đắn, ngôi nhà mơ ước này là tổ ấm hoàn hảo tránh xa sự hối hả và nhộn nhịp của thành phố. Dùng bữa và nghỉ ngơi giữa lòng thiên nhiên - ngâm mình trong bồn tắm bằng gỗ của riêng bạn, kết thúc quá trình đọc sách quá hạn bên ban công, hoặc thư giãn trên những chiếc giường cỡ lớn thoải mái nhất trong ngôi nhà 3 phòng ngủ này. Nếu tâm hồn bạn đảm bảo điều đó, hãy bơi trong làn nước lạnh vĩnh viễn của dòng sông nhỏ của chính bạn!  Có hai phòng nằm ở tầng trên, một phòng có ban công riêng nhìn ra sông. Cả hai phòng đều có giường cỡ lớn, phòng đầu tiên có hai giường kéo đơn. Cả hai tầng đều có đầy đủ phòng tắm, tầng trên có bồn tắm bằng gỗ. Sân ven sông cũng có vòi sen riêng. Có hai chiếc võng hoàn hảo để thư giãn bên hiên ven sông. Chỉ vòi hoa sen trên cùng có nước nóng. Tất cả các nhà vệ sinh đều có chậu rửa vệ sinh. Tầng dưới là một không gian ngoài trời lớn, nơi bạn có thể tìm thấy phòng khách, nhà bếp, một chiếc giường khác và một ban công khác. Khách phải quen với việc chia sẻ tầng dưới với nhau vì đây là một không gian mở.', 'Teahouse Homestay', 2, 3, 1950000, 1, '237380893_376420447285275_7250869604828108196_n.png', 4);
INSERT INTO house_renting.house (house_id, address, des, house_name, numBathrooms, numBedrooms, price, type_id, sourcePath, owner_id) VALUES (13, 'Đà Nẵng', 'TREEHOUSE đã được xây dựng xung quanh một Cây cổ thụ 100 năm tuổi tuyệt đẹp, nằm tự nhiên. Được thiết kế trên 2 Tầng với 2 Sân thượng & lối đi thẳng ra bãi biển, TREEHOUSE lý tưởng cho các cặp vợ chồng, bạn bè tốt hoặc thậm chí một người lớn và trẻ em. (dưới sự giám sát) Thức dậy mỗi sáng để ngắm nhìn toàn cảnh Biển và âm thanh của đại dương! Bước qua khe hở trong bức tường đá tự nhiên được xây bằng tay tuyệt đẹp lên khu vực sân hiên bằng đá của riêng bạn, nơi bạn có thể ngồi và thưởng thức quang cảnh hùng vĩ, một hoặc hai ly cocktail & cảnh hoàng hôn tuyệt vời! Hoặc đi dạo dọc theo bãi biển và tận hưởng những bàn chân đầy cát! Cây tích hợp vào không gian Phòng tắm & cho phép các đường cong tự nhiên của Thân & Nhánh chảy vào và ra khỏi không gian, tạo nên một nét độc đáo và siêu mát mẻ.', 'TREEHOUSE', 1, 1, 4500000, 1, '239884788_828911371096727_7339311595720474772_n.png', 4);
INSERT INTO house_renting.house (house_id, address, des, house_name, numBathrooms, numBedrooms, price, type_id, sourcePath, owner_id) VALUES (15, 'Đà Lạt', 'Khách sạn vẫn giữ nguyên định dạng kiến trúc ban đầu nhưng thiết kế tiên phong táo bạo bên trong đáp ứng nhu cầu của người hiện đại về chất lượng cuộc sống cao. Sự khác biệt lớn nhất giữa nó và khách sạn đô thị hiện tại là mức độ thoải mái không bị hạn chế, và nó khéo léo tránh cảm giác ngột ngạt của thiết kế hiện đại, kết hợp giữa cổ kính và hiện đại, tối đa hóa điểm mạnh và loại bỏ điểm yếu, và cung cấp cho khách du lịch một nơi ở và thư giãn độc đáo môi trường. Khách sạn đã phương tiện hỗ trợ. thanh trà giải trí trung tâm thể dục, hồ bơi nước nóng ngoài trời và các cơ sở vui chơi giải trí khác. Ngoài ra còn có những ngôi nhà trên cây tinh tế ẩn mình trong rừng thông, những ngôi nhà trên mặt nước, nơi bạn có thể đếm sao trên giường, là khách sạn lý tưởng cho khách trong và ngoài nước đến giải trí, nghỉ dưỡng, chăm sóc sức khỏe, hội thảo và công tác.', 'Veque Homestay', 1, 2, 980000, 1, '240386785_4339465219482561_7373039482131456488_n.png', 4);
INSERT INTO house_renting.house (house_id, address, des, house_name, numBathrooms, numBedrooms, price, type_id, sourcePath, owner_id) VALUES (16, 'Rừng Nam Cát Tiên, Đồng Nai', 'Nằm ở rìa của một khu rừng trong một công viên tự nhiên được bảo vệ, cao 8m và có thể tiếp cận bởi một cây cầu đi bộ 35m, cabin sang trọng gợi nhớ này đang chờ bạn. Sự thoải mái và xa xỉ là điều bắt buộc. Riêng Jacuzzi và phòng xông hơi, 180 giường, vòi sen đôi, TV/kênh kết nối +, bếp nhỏ đầy đủ... Tại đây, mọi thứ được thực hiện để cung cấp cho bạn, trong một môi trường đặc biệt, một dấu ngoặc đơn nhẹ nhàng cho hai và một khoảnh khắc độc đáo trong hoàn toàn riêng tư', 'HOUSEINFOREST', 4, 5, 6200000, 1, '239332070_554709089209578_4857933908163248421_n.png', 4);
INSERT INTO house_renting.house (house_id, address, des, house_name, numBathrooms, numBedrooms, price, type_id, sourcePath, owner_id) VALUES (17, 'Đà Nẵng', 'Biệt thự có ba tầng, một sân trong tách biệt, một hồ bơi riêng, bãi đậu xe, một không gian giải trí và sinh hoạt rộng lớn, và một máy chơi mạt chược tự động. Nhận phòng và tận hưởng clubhouse book bar, phòng tập thể dục, câu lạc bộ trẻ em trong nhà trong khu biệt thự. Bạn có thể nấu ăn miễn phí (bạn cần phải dọn dẹp nhà bếp sau đó, nếu không bạn sẽ phải trả 500-1000 nhân dân tệ cho việc dọn dẹp), đồ dùng nhà bếp đầy đủ, được trang bị gia vị cơ bản và dịch vụ quản gia 24 giờ.', 'The Hill Resort', 6, 7, 4800000, 2, '240384792_962136177677641_3952633822263350699_n.png', 4);
INSERT INTO house_renting.house (house_id, address, des, house_name, numBathrooms, numBedrooms, price, type_id, sourcePath, owner_id) VALUES (18, 'Phú Quốc', 'Ngôi nhà làm nổi bật phong cách Đông Nam Á đích thực, tất cả các vật liệu xây dựng được làm bằng đá tự nhiên và gỗ đóng tàu Đông Nam Á, nguyên bản, mang lại cảm giác thanh thản, ổn định và sang trọng. Biệt thự hồ bơi riêng lẻ, kiến trúc Đông Nam Á tổng thể, hoàn hảo. Thiết kế sân vườn tinh tế, môi trường yên tĩnh, thanh lịch, xanh hóa đến 60%, không khí trong lành và tự nhiên. Phòng suite sang trọng, kính từ sàn đến trần, cửa sổ rộng rãi và sáng sủa, gió, rừng nhiệt đới xanh tươi và rừng mưa nhiệt đới.', 'Phú Quốc Resort', 5, 6, 6800000, 2, '240423418_182160070672135_7318840560999797290_n.png', 4);
INSERT INTO house_renting.house (house_id, address, des, house_name, numBathrooms, numBedrooms, price, type_id, sourcePath, owner_id) VALUES (19, 'Đà Lạt', 'Phong cách thuần Đông Nam Á, tất cả vật liệu xây dựng đều bằng đá tự nhiên và gỗ đóng tàu Đông Nam Á được làm theo hương vị nguyên bản, tạo cho người nhìn cảm giác bình lặng, vững chãi và sang trọng. Biệt thự hồ bơi riêng dành cho một gia đình, tổng thể phong cách kiến trúc Đông Nam Á. Thiết kế sân vườn thật khéo léo, môi trường yên tĩnh và trang nhã, độ phủ xanh cao đến 60%, không khí trong lành và tự nhiên. Dãy phòng sang trọng, kính suốt từ trần đến sàn, rộng rãi sáng sủa, mở cửa sổ ra là có thể ngắm cảnh, hóng gió, rừng nhiệt đới rậm rạp, xanh rì rào rạt, mang đậm phong cách rừng mưa nhiệt đới.', 'Rex Hotel', 3, 3, 1500000, 2, '239648835_316127716928966_5657209856625241476_n.png', 4);
INSERT INTO house_renting.house (house_id, address, des, house_name, numBathrooms, numBedrooms, price, type_id, sourcePath, owner_id) VALUES (20, 'Ba Vì', 'Điểm nhấn của ngôi nhà là phong cách Đông Nam Á đích thực, tất cả các vật liệu xây dựng đều được làm từ đá tự nhiên và gỗ đóng tàu Đông Nam Á, được làm từ hương vị nguyên bản và mang lại cảm giác bình yên, ổn định và sang trọng. Biệt thự hồ bơi riêng, kiến trúc Đông Nam Á tổng thể. Thiết kế sân vườn khéo léo, môi trường yên tĩnh và thanh lịch, cây xanh lên đến 60%, không khí trong lành và tự nhiên. Phòng Suite sang trọng, kính từ sàn đến trần, rộng rãi và sáng sủa, tầm nhìn ra cửa sổ, thói quen thoáng đãng, rừng mưa nhiệt đới tươi tốt, cây xanh tươi tốt và rừng mưa nhiệt đới.', 'Sunland Hotel', 2, 2, 860000, 2, '240641330_1553864951623901_456320504098813953_n.png', 4);
INSERT INTO house_renting.house (house_id, address, des, house_name, numBathrooms, numBedrooms, price, type_id, sourcePath, owner_id) VALUES (21, 'Đà Lạt', 'Poolhouse nhỏ nằm ngay cạnh hồ bơi, có thể dùng lẩu ngay bên cạnh.', 'Poolhouse', 1, 2, 1700000, 3, '238210193_989620098492029_4893239137375222043_n.png', 4);
INSERT INTO house_renting.house (house_id, address, des, house_name, numBathrooms, numBedrooms, price, type_id, sourcePath, owner_id) VALUES (22, 'Ba Vì', 'The Tiny House cách vườn quốc gia Ba Vì 5 phút đi xe đạp. The Tiny House cung cấp cho bạn mọi thứ bạn cần để có một kỳ nghỉ hoàn hảo ở Ba Vì. Tài sản nơi có Ngôi nhà nhỏ độc đáo do một mình bạn sử dụng. Trang trí rất hiện đại và được trang bị với sự chú ý đến từng chi tiết. Sân hiên lớn với nhiều lựa chọn chỗ ngồi và thư giãn là nơi lý tưởng để thư giãn.', 'Tiny House', 1, 2, 960000, 3, '235512586_351349623132126_4034974786344535736_n.png', 4);
INSERT INTO house_renting.house (house_id, address, des, house_name, numBathrooms, numBedrooms, price, type_id, sourcePath, owner_id) VALUES (23, 'Tam Đảo, Vĩnh Phúc', 'Bạn đã luôn muốn ở trong một ngôi nhà nhỏ? Đây là một ngôi nhà dành cho bạn. Ngôi nhà nhỏ ấm cúng ở trung tâm Vĩnh Phúc. Vị trí rất yên tĩnh. Có chỗ để xe trước nhà. Ngôi nhà có khu vực ngủ nghỉ (2,00 x 2,00 m) trên gác lửng phía trên. Nhà bếp nhỏ hiện đại được trang bị bếp nấu ăn, máy pha cà phê, máy nướng bánh mì, ấm đun nước, bát đĩa / đồ dùng nhà bếp và cả máy giặt .Ghế sofa nhỏ với bàn phòng khách và TV FullHD với truy cập Simpli TV.Có WiFi. Phòng tắm có vòi sen và toilet (có sẵn khăn tắm)', 'Mini Villa', 1, 1, 590000, 3, '235835282_933670983884693_4385509184058934074_n.png', 4);
INSERT INTO house_renting.house (house_id, address, des, house_name, numBathrooms, numBedrooms, price, type_id, sourcePath, owner_id) VALUES (24, 'Đã Nẵng', 'Cabin của chúng tôi nằm tại Đà Nẵng, nhà hàng của chúng tôi cách đó khoảng 500m và có thể đi bộ hoặc đi bằng ô tô. Bạn có toàn bộ túp lều với một khu vườn lớn cho riêng mình.Nhà có một nhà bếp với cửa sổ hình ảnh lớn. Một bếp củi và nhà bếp. Một chiếc giường gia đình (phòng thông nhau) có kích thước 280x200m hoặc 2x140x200 và một chiếc 180x200 rất lý tưởng cho tổng cộng 6 người. Giường ngủ gia đình cũng có thể được sử dụng như một chiếc giường ban ngày.', 'Slow House', 1, 2, 1400000, 3, '236244965_858378961466583_7063314153976017045_n.png', 4);
INSERT INTO house_renting.house (house_id, address, des, house_name, numBathrooms, numBedrooms, price, type_id, sourcePath, owner_id) VALUES (25, 'Đã Nẵng', 'Nhà nằm trên bờ biển quốc gia của thành phố Đà Nẵng. Thiết kế nhà tận dụng sự chênh lệch về chiều cao địa hình, hình thang theo chiều ngang và chiều dọc, với bố trí cầu thang đảm bảo tầm nhìn ra biển trong hầu hết các không gian.Xét về sự kết hợp giữa chức năng kinh doanh, tiệc tùng và nghỉ dưỡng, mỗi phòng đều có một không gian tầng hầm đa năng với một khu vườn và bể bơi riêng khổng lồ, sân thượng có tầm nhìn ra biển, v.v. Tận hưởng ban công có kích thước quá lớn nhìn ra biển, đồ nội thất riêng tuyệt vời và bồn tắm khô và ướt riêng biệt để có thời gian lưu trú chu đáo.', 'Risemount Resort', 2, 3, 7500000, 4, '240674090_367692901763040_7592123157356211122_n.png', 4);
INSERT INTO house_renting.house (house_id, address, des, house_name, numBathrooms, numBedrooms, price, type_id, sourcePath, owner_id) VALUES (26, 'Phú Quốc', '30 mét vuông và 180 độ kính tròn từ sàn đến trần mặt trước hướng biển toàn cảnh biển nổi phòng giường lớn, phòng này rộng 58 mét vuông, mặt tiền hướng biển 180 độ kính tròn từ sàn đến trần toàn biển xem để nhìn thấy biển, những con sóng màu xanh của những con sóng có thể được nhìn thấy. cùng lúc đó, nó được trang bị một chiếc ghế kính treo để ngắm biển để giải trí, và tận hưởng những giá trị đồng tiền xem của biển trong khi treo trong không khí. Phòng ngủ được trang bị ghế sofa tre, trải chiếu tatami bằng da để thư giãn, máy chiếu 100 inch siêu thị, giường đôi 1,8m kiểu châu Âu, bồn tắm có ghế dài, đèn đỏ ròng và nhiều thiết bị khác nhau. Có 10m2 nhà vệ sinh khô ướt riêng biệt.', 'Vinpearl Discovery', 2, 2, 4300000, 4, '239041940_242234031130050_8989165029533354077_n.png', 4);
INSERT INTO house_renting.house (house_id, address, des, house_name, numBathrooms, numBedrooms, price, type_id, sourcePath, owner_id) VALUES (27, 'Nha Trang, Khánh Hòa', 'Đây là ngôi nhà nằm giữa biển ở Nhà Trang và là nơi ngắm biển đẹp nhất. Căn hộ đơn có diện tích nhà ở khoảng 50m2, phòng này có thể ở được 2 người lớn và 1 trẻ em (dưới 5 tuổi). Nội thất trong các phòng đều là các thương hiệu cao cấp của Châu Âu, lối trang trí tiên phong và độc đáo, là tác phẩm đại diện cho những ngôi nhà sang trọng. Phòng có ban công hướng biển siêu sang chảnh, ngoài ban công còn có bồn tắm ngoài trời kiểu "net nổi tiếng", bên trong phòng là thiết bị vòi hoa sen đáng để trải nghiệm! Trong ngôi nhà này, bạn có thể nhìn thấy cảnh biển khi nằm trên giường, và bạn có thể nhìn thấy cảnh biển đẹp nhất của vịnh Tam Á. Có một hồ bơi vô cực "dành cho người nổi tiếng" ở tầng một, lối đi dạo bên bờ biển và sân chơi cho trẻ em, tất cả đều là những nơi tuyệt vời để chụp ảnh.', 'Famiana Resort', 1, 2, 2500000, 4, '239909001_578200160024921_8825093853601472062_n.png', 4);
INSERT INTO house_renting.house (house_id, address, des, house_name, numBathrooms, numBedrooms, price, type_id, sourcePath, owner_id) VALUES (28, 'Phú Quốc', 'Nằm trên tầng hai của biệt thự, phòng trên trời đẩy qua cửa và rèm điện từ từ mọc lên. Gọi cho Tmall Elves và bạn có thể chơi nhạc yêu thích của mình. Sau đó tắm cánh hoa hồng, rót một ly rượu vang và từ từ thưởng thức hoàng hôn. Giường tròn lớn 2,2 mét hoàn hảo cho các cặp đôi trong tuần trăng mật của họ. Nằm trên tầng hai của biệt thự, phòng sky là một chiếc giường tròn cao mềm mại và thoải mái, nằm trên nó hướng ra biển. Cảm giác như bạn đang ngủ giữa biển, phòng tắm và nhà vệ sinh đều hướng ra biển.Có một phòng tắm trong nhà, nơi bạn có thể tắm, nghe nhạc, nếm rượu vang và ngắm thủy triều lên xuống.Buổi tối, bạn có thể ngắm hoàng hôn đẹp nhất từ ban công hướng ra biển.', 'Daisy Village Resort', 1, 1, 5600000, 4, '240120706_847651519288950_209104293051687709_n.png', 4);
INSERT INTO house_renting.house (house_id, address, des, house_name, numBathrooms, numBedrooms, price, type_id, sourcePath, owner_id) VALUES (29, 'Tam Đảo, Vĩnh Phúc', 'Nằm cách trung tâm Vĩnh Phúc chỉ 10 phút về phía Nam, là nơi nghỉ dưỡng hoàn hảo cho các cặp vợ chồng hoặc một gia đình nhỏ đang tìm kiếm một kỳ nghỉ riêng tư và thư giãn. Ngôi nhà khung A rất độc đáo này có 3 phòng ngủ, 2 phòng tắm và có nhà bếp đầy đủ tiện nghi, khu vực giặt là và sinh hoạt, mở ra sân hiên rộng lớn với khu vực ăn uống ngoài trời, phòng tắm nắng và tầm nhìn tuyệt đẹp ra đại dương. Có một hồ bơi riêng rộng lớn được bao quanh bởi một sân phơi nắng cùng với sân tennis riêng của bạn, biến nơi đây trở thành nơi nghỉ dưỡng riêng tư của riêng bạn trong thiên đường.', 'Wood Homestay', 2, 3, 3500000, 5, '236139785_4292658004147414_1400415731040674324_n.png', 4);
INSERT INTO house_renting.house (house_id, address, des, house_name, numBathrooms, numBedrooms, price, type_id, sourcePath, owner_id) VALUES (30, 'Ba Vì', 'Trang trại Aikya nằm ẩn mình giữa cây xanh. Quên đi sự hối hả và nhộn nhịp của cuộc sống thành phố và tận hưởng môi trường thanh bình. Những bài hát của những con chim không bao giờ bị lạc nhịp. Những câu chuyện không bao giờ kết thúc mà bạn chia sẻ, xem những con đom đóm nhảy múa cho bạn. Phần hay nhất về cabin khung A trong rừng này là tầm nhìn ra những cái cây cao, tại khu vực gác xép khi bạn thức dậy. Aikya là một Nông trại chứ không phải là một khu nghỉ dưỡng với đầy đủ tiện nghi.Nơi đây là nơi trú ngụ của nhiều loại chim hoang dã và là thiên đường cho những người quan sát chim. Chúng tôi có nuôi gia súc, cừu, chó trong trang trại. Ngôi nhà gỗ riêng dành riêng cho khách bao gồm không gian tiếp khách với bộ ghế sofa, bàn Coffe, bếp mở.', 'Aikya Farm', 2, 4, 2900000, 5, '240532420_131480605810249_7473940566732570666_n.png', 4);
INSERT INTO house_renting.house (house_id, address, des, house_name, numBathrooms, numBedrooms, price, type_id, sourcePath, owner_id) VALUES (31, 'Đà Lạt', 'Bạn sẽ có được toàn bộ ngôi nhà truyền thống Hàn Quốc. Nghĩa là bạn không được chia sẻ với bất kỳ ai khác. Không gian rất rộng đủ để ở cho gia đình. Bạn có thể thư giãn tránh xa cuộc sống bận rộn trong nhà chúng tôi. Bạn có thể trải nghiệm tuyệt vời với thiên nhiên tươi đẹp và không khí mát mẻ tại khu vườn và núi Bukhan gần nhà tôi. Khi du khách đến nhà tôi, họ cảm thấy thực sự khỏe mạnh và hạnh phúc. Nó giống như một khu nghỉ dưỡng để bạn có thể tỉnh dậy với tiếng chim hót và không khí trong lành. Chúng tôi thực sự yêu thích gặp gỡ mọi người và chúng tôi thường ở đây để chào đón bạn và những người xung quanh khi bạn đến nơi. Chúng tôi tôn trọng quyền riêng tư của bạn trong thời gian bạn ở nhưng cũng luôn sẵn sàng nếu bạn cần bất kỳ điều gì. Đó là một cách thú vị để dành thời gian với khách của chúng tôi và chúng tôi sẵn sàng cung cấp cho bạn gợi ý về địa điểm cần đi tùy thuộc vào sở thích của bạn. Chúng tôi là nơi dành cho bạn!', 'General Homestay', 1, 2, 1900000, 5, '236968639_376143704158381_8108189070007628685_n.png', 4);
INSERT INTO house_renting.house (house_id, address, des, house_name, numBathrooms, numBedrooms, price, type_id, sourcePath, owner_id) VALUES (32, 'Ba Vì', 'Ngôi nhà có 4 lều và nhà gỗ độc lập. Ngoài ra còn có sân hiên thư giãn trên những ngôi nhà gỗ. khoảng cách. Mỗi lều đều có giường lớn 1,8m * 2m thoải mái, điều hòa độc lập, phòng tắm riêng, nước nóng 24/24, sau khi nhận phòng, bạn có thể trút bỏ mệt mỏi và ngủ một giấc thật trọn vẹn. Phòng được trang bị các đồ dùng sinh hoạt như ấm đun nước điều hòa đáp ứng nhu cầu sinh hoạt. Phòng tắm sạch sẽ, gọn gàng, đồ dùng vệ sinh đầy đủ, bạn có thể tự tin sử dụng khăn tắm, khăn tắm đã khử trùng, nhớ làm khô tóc bằng máy sấy. Hãy chăm sóc bản thân ngay cả trong chuyến đi nhé! Sân thượng: Ngồi trên sân thượng của ngôi nhà gỗ lều, trước mặt bạn là bãi cỏ rộng lớn, ngôi nhà kính tinh xảo, xa xa là những ngọn núi trập trùng, khi đêm về bạn bị bao vây bởi côn trùng và chim chóc, nhìn lên . bầu trời đầy sao Nó dường như được sống trong tự nhiên, nếu bạn thức dậy sớm hơn, bạn có thể cảm nhận được ánh nắng mặt trời đầu tiên trong ngày, ấm áp và ấm cúng.', 'Blue House', 1, 2, 850000, 5, '235835282_385303943006262_4221522780603304095_n.png', 4);